version: '2'
services:
    chartbusters-app:
        image: chartbusters
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://chartbusters-mysql:3306/chartbusters?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=chartbusters-elasticsearch:9300
        ports:
            - 8080:8080
    chartbusters-mysql:
        extends:
            file: mysql.yml
            service: chartbusters-mysql
    chartbusters-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: chartbusters-elasticsearch
